version: '3.9'
services:
  pds:
    container_name: pds
    image: ghcr.io/bluesky-social/pds
    ports:
      - "32850:3000"    
    restart: unless-stopped
    volumes:
        - /mnt/docker/bsky/pds/pds:/pds
